"""
Pydantic data models for meta-analysis planning and execution.

The meta-analysis step is intentionally decoupled from ExtractionOutput. Its
inputs are cleaned CSV files plus the review PICO context.
"""

from enum import Enum
from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field

from autometa.schemas.models import PICODefinition


class MetaAnalysisType(str, Enum):
    """High-level data family for a meta-analysis dataset."""

    DICHOTOMOUS = "dichotomous"
    CONTINUOUS = "continuous"
    GENERIC_EFFECT = "generic_effect"


class EffectMeasure(str, Enum):
    """Supported effect measures."""

    OR = "OR"
    RR = "RR"
    RD = "RD"
    MD = "MD"
    SMD = "SMD"
    HEDGES_G = "Hedges_g"


class EffectSource(str, Enum):
    """Where study-level effects should be derived from."""

    ARM_LEVEL_DATA = "arm_level_data"
    REPORTED_EFFECT_AND_CI = "reported_effect_and_ci"
    REPORTED_EFFECT_AND_SE = "reported_effect_and_se"
    REPORTED_EFFECT_AND_VARIANCE = "reported_effect_and_variance"


class MetaModelType(str, Enum):
    """Pooling model selection strategy."""

    FIXED = "fixed"
    RANDOM = "random"
    AUTO_BY_I2 = "auto_by_i2"


class FixedEffectMethod(str, Enum):
    """Supported fixed-effect pooling methods."""

    INVERSE_VARIANCE = "inverse_variance"
    MANTEL_HAENSZEL = "mantel_haenszel"


class RandomEffectsMethod(str, Enum):
    """Supported random-effects tau-squared estimators."""

    DERSIMONIAN_LAIRD = "dersimonian_laird"
    RESTRICTED_MAXIMUM_LIKELIHOOD = "restricted_maximum_likelihood"


class ContinuityCorrectionApplyWhen(str, Enum):
    """When to apply a continuity correction for sparse dichotomous data."""

    ZERO_CELL = "zero_cell"
    ALWAYS = "always"
    NEVER = "never"


class MetaAnalysisColumns(BaseModel):
    """
    Mapping from semantic roles to CSV column names.

    Only fields needed by the selected analysis_type/effect_source are required
    at runtime. The planner should leave unrelated fields as null.
    """

    study_label: Optional[str] = Field(default=None, description="Study name / first author column")
    year: Optional[str] = Field(default=None, description="Publication year column")
    title: Optional[str] = Field(default=None, description="Study title column")
    outcome: Optional[str] = Field(default=None, description="Outcome or subgroup label column")

    experimental_events: Optional[str] = None
    experimental_total: Optional[str] = Field(
        default=None,
        description="Experimental/intervention sample size column",
    )
    control_events: Optional[str] = None
    control_total: Optional[str] = Field(
        default=None,
        description="Control/comparator sample size column",
    )

    experimental_mean: Optional[str] = None
    experimental_sd: Optional[str] = None
    control_mean: Optional[str] = None
    control_sd: Optional[str] = None

    effect: Optional[str] = Field(default=None, description="Reported study-level effect column")
    ci_lower: Optional[str] = Field(default=None, description="Lower bound of reported 95% CI")
    ci_upper: Optional[str] = Field(default=None, description="Upper bound of reported 95% CI")
    standard_error: Optional[str] = Field(default=None, description="Reported standard error column")
    variance: Optional[str] = Field(default=None, description="Reported variance column")


class PoolingModelSpec(BaseModel):
    """Pooling model and heterogeneity-driven model switching rule."""

    type: MetaModelType = MetaModelType.AUTO_BY_I2
    fixed_method: FixedEffectMethod = FixedEffectMethod.INVERSE_VARIANCE
    random_method: RandomEffectsMethod = RandomEffectsMethod.DERSIMONIAN_LAIRD
    i2_threshold: float = Field(default=50.0, ge=0.0, le=100.0)


class ContinuityCorrectionSpec(BaseModel):
    """Continuity correction for dichotomous outcomes."""

    enabled: bool = True
    value: float = Field(default=0.5, ge=0.0)
    apply_when: ContinuityCorrectionApplyWhen = ContinuityCorrectionApplyWhen.ZERO_CELL


class MetaAnalysisOutputSpec(BaseModel):
    """Requested result sections."""

    include_study_effects: bool = True
    include_weights: bool = True
    include_pooled_effect: bool = True
    include_heterogeneity: bool = True
    include_output_csv: bool = True
    include_prediction_interval: bool = True
    include_leave_one_out: bool = True
    include_subgroup: bool = True
    include_forest_plot: bool = True


class MetaAnalysisMethodPlan(BaseModel):
    """
    User-reviewable method plan generated by the planner and confirmed before
    code generation/execution.
    """

    csv_file: str = Field(description="Name of the cleaned CSV file this plan applies to")
    outcome_name: str = Field(default="", description="Outcome being synthesized")
    method_text: str = Field(description="Human-readable analysis method shown to users")

    analysis_type: MetaAnalysisType
    effect_measure: EffectMeasure
    effect_source: EffectSource
    model: PoolingModelSpec = Field(default_factory=PoolingModelSpec)
    columns: MetaAnalysisColumns
    subgroup_column: Optional[str] = None
    continuity_correction: Optional[ContinuityCorrectionSpec] = None
    exclusion_rules: List[str] = Field(default_factory=list)
    output: MetaAnalysisOutputSpec = Field(default_factory=MetaAnalysisOutputSpec)

    assumptions: List[str] = Field(
        default_factory=list,
        description="Planner assumptions that users should review before running",
    )
    warnings: List[str] = Field(
        default_factory=list,
        description="Potential data or method issues detected by the planner",
    )


class CSVSummary(BaseModel):
    """Compact CSV profile supplied to the planner prompt."""

    csv_file: str
    columns: List[str]
    row_count: int
    sample_rows: List[Dict[str, Any]] = Field(default_factory=list)


class MetaAnalysisPlanRequest(BaseModel):
    """Request body for generating method plans from cleaned CSV profiles."""

    pico: PICODefinition
    csv_summaries: List[CSVSummary]
    user_hint: str = Field(default="", description="Optional user guidance for method selection")


class MetaAnalysisPlanResponse(BaseModel):
    """Planner response containing one method plan per CSV file."""

    plans: List[MetaAnalysisMethodPlan] = Field(default_factory=list)


class MetaAnalysisRunRequest(BaseModel):
    """Request body for code generation and calculation after user confirmation."""

    pico: PICODefinition
    plans: List[MetaAnalysisMethodPlan]


class StudyEffectResult(BaseModel):
    """Calculated study-level effect and weight."""

    study_label: str = ""
    year: Optional[str] = None
    title: Optional[str] = None
    outcome: Optional[str] = None
    effect: float
    standard_error: float
    ci_lower: float
    ci_upper: float
    weight_percent: Optional[float] = None


class HeterogeneityResult(BaseModel):
    """Heterogeneity statistics for one meta-analysis."""

    q: Optional[float] = None
    df: Optional[int] = None
    p_value: Optional[float] = None
    i2_percent: Optional[float] = None
    tau2: Optional[float] = None
    tau: Optional[float] = None


class PooledEffectResult(BaseModel):
    """Pooled effect estimate for one meta-analysis."""

    model_used: MetaModelType
    effect_measure: EffectMeasure
    effect: float
    standard_error: float
    ci_lower: float
    ci_upper: float
    z_value: Optional[float] = None
    p_value: Optional[float] = None


class PredictionIntervalResult(BaseModel):
    lower: float
    upper: float


class LeaveOneOutResult(BaseModel):
    omitted_study: str
    pooled_effect: PooledEffectResult
    heterogeneity: HeterogeneityResult


class SubgroupPoolResult(BaseModel):
    label: str
    study_count: int
    pooled_effect: PooledEffectResult
    heterogeneity: HeterogeneityResult


class SubgroupAnalysisResult(BaseModel):
    groups: List[SubgroupPoolResult] = Field(default_factory=list)
    between_group_q: float
    between_group_df: int
    between_group_p_value: float


class GeneratedFigureResult(BaseModel):
    file_id: str
    filename: str
    mime_type: str


class MetaAnalysisDatasetResult(BaseModel):
    """Complete result for a single cleaned CSV file."""

    csv_file: str
    outcome_name: str = ""
    study_effects: List[StudyEffectResult] = Field(default_factory=list)
    pooled_effect: Optional[PooledEffectResult] = None
    heterogeneity: Optional[HeterogeneityResult] = None
    prediction_interval: Optional[PredictionIntervalResult] = None
    leave_one_out: List[LeaveOneOutResult] = Field(default_factory=list)
    subgroup_analysis: Optional[SubgroupAnalysisResult] = None
    figure_files: List[GeneratedFigureResult] = Field(default_factory=list)
    output_csv: Optional[str] = Field(default=None, description="CSV text generated by the runner")
    logs: List[str] = Field(default_factory=list)
    warnings: List[str] = Field(default_factory=list)


class MetaAnalysisRunResponse(BaseModel):
    """Runner response after code generation and execution."""

    results: List[MetaAnalysisDatasetResult] = Field(default_factory=list)
    generated_code: Dict[str, str] = Field(
        default_factory=dict,
        description="Generated Python code keyed by CSV file name",
    )
